#server:
#  port: 8080
#

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.91.238.162:3306/mydb?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root

#logging:
#  level: info
#com:
#  baomidou:
#    mybatisplus:
#      samples:
#        quickstart: debug

#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
